### ISSUE TITLE
'cargo install neowatch' fails on Windows

### ISSUE THREAD

**Issue by olivier-fs** [kilpkonn/neowatch#2]
Hi!
Just tried to install neowatch on my box (rust 1.63.0 and 1.65.0-nightly)

On stable , 'cargo install neowatch' fails with 4 errors :

error[E0432]: unresolved import `libc::SIGHUP`
 --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\signal.rs:1:41
  |
1 | use libc::{c_int, sighandler_t, signal, SIGHUP, SIGINT, SIGTERM};
  |                                         ^^^^^^ no `SIGHUP` in the root

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\main.rs:1:12
  |
1 | #![feature(termination_trait_lib)]
  |            ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\main.rs:2:12
  |
2 | #![feature(int_abs_diff)]
  |            ^^^^^^^^^^^^

error[E0053]: method `report` has an incompatible type for trait
  --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\error.rs:48:24
   |
48 |     fn report(self) -> i32 {
   |                        ^^^
   |                        |
   |                        expected struct `ExitCode`, found `i32`
   |                        help: change the output type to match the trait: `ExitCode`
   |
   = note: expected fn pointer `fn(Exit<'_>) -> ExitCode`
              found fn pointer `fn(Exit<'_>) -> i32`

On nightly (with the features that solves 2 of the 4 above errors), 'cargo install neowatch' fails with the 2 remaining errors :

error[E0432]: unresolved import `libc::SIGHUP`
 --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\signal.rs:1:41
  |
1 | use libc::{c_int, sighandler_t, signal, SIGHUP, SIGINT, SIGTERM};
  |                                         ^^^^^^ no `SIGHUP` in the root

error[E0053]: method `report` has an incompatible type for trait
  --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\neowatch-0.1.3\src\error.rs:48:24
   |
48 |     fn report(self) -> i32 {
   |                        ^^^
   |                        |
   |                        expected struct `ExitCode`, found `i32`
   |                        help: change the output type to match the trait: `ExitCode`
   |
   = note: expected fn pointer `fn(Exit<'_>) -> ExitCode`
              found fn pointer `fn(Exit<'_>) -> i32`

2nd error : error message is explicit, should be easy to solve.

1sr error : off course libc has SIGHUP etc. only for linux/*bsd/solaris etc. Unices.
There are crates (e.g. ctrlc) to get portable CTRL-C handlers (i.e. not having to deal with winapi SetConsoleCtrlHandler on Windows).

Hope this helps.

**Comment by kilpkonn** [comment]
Thank you for detailed description.
I've updated the code on `main` to compile with stable rust on latest toolchain.
I've also added support for windows in `windows_support` branch via `ctrlc` crate as you suggested.
Would you mind testing it before I merge it to `main`?
```bash
cargo install --git https://github.com/kilpkonn/neowatch.git --branch windows_support
```
should do the trick :)

**Comment by olivier-fs** [comment]
Wow that was fast !
I confirm : build OK with rust stable (1.63.0), no need for nightly.
I think you can close this issue after the merge in main.
Great job !
